name: techinng
description: "A Flutter app to help university students practice soft skills"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP Client
  dio: ^5.4.0
  
  # Animations
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0

  
  # Typography
  google_fonts: ^6.1.0
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/lottie/
    
    # Home/Dashboard assets (Villa)
    - assets/images/avatar2.png
    - assets/images/avion.png
    - assets/images/avion5.png
    - assets/images/bell2.png
    - assets/images/cards.png
    - assets/images/casa1.png
    - assets/images/newspapper.png
    - assets/images/pencil.png
    - assets/images/rocket3.png
    - assets/images/star4.png
    - assets/images/tareas2.png
    
    # Onboarding assets (Edu)
    - assets/images/boar1.png
    - assets/images/boar2.png
    - assets/images/boar3.png
    - assets/images/boar4.png
    - assets/images/flechanext.png
    
    # Lottie animations
    - assets/lottie/fire.json