name: techinng
description: "A Flutter app to help university students practice soft skills"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP Client
  dio: ^5.4.0
  
  # Animations
  lottie: ^2.7.0
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

 
  
